# Generated by Django 5.1 on 2024-09-09 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='requested_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 9, 9, 14, 3, 31, 946818)),
        ),
    ]
